Algoritmo "semnome"
//
Var
   Idade : vetor [1..5] de Inteiro
   nome : vetor [1..5] de  Caractere
   i: inteiro
Inicio
   Para i de 1 ate 5 faca

      Escreva ("Digite seu nome:")
      leia (Nome[i])

      Escreva ("Digite sua idade:")
      leia (Idade[i])
      
      Limpatela

   Fimpara

   Para i de 1 ate 5 faca
      Escreval("Nome:", Nome[i])
      Escreval("Idade:", Idade[i])

   Fimpara

Fimalgoritmo